- name: Install apache # name of teh playbook
  hosts: web # target
  become: yes # TRUE True# Needs sudo/adminstrator access
  
  vars:
    apache_port: 9090
    
  
  tasks:
    - name: Apache installation
      dnf:
        name: httpd
        state: present
    - name: Start service httpd, if not started
      service:
        name: httpd
        state: started
    - name: Copy file with owner and permissions
      copy:
        src: /home/ec2-user/ansible_learning/index.html
        dest: /var/www/html/
    - name: Ensure the default Apache port is "{{ apache_port }}"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: "Listen {{ apache_port }}"
    - name: ReStart service httpd
      service:
        name: httpd
        state: restarted
