- name: Install apache in amazon linux and ubuntu 
  hosts: web
  become: yes   
  
  tasks:
    - name: Install apache in amazon linux
      dnf:
        name: httpd
        state: present
      when: ansible_facts.distribution == "Amazon"
    - name: Install apache in ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_facts.distribution == "Ubuntu"
